#!/usr/bin/env bash
# transfers a file from our client to a server using scp

if [ "$#" -ne 4 ]; then
        echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

FILE=$1
SERVER_IP=$2
USERNAME=$3
PRIVATE_KEY_PATH=$4

scp -o StrictHostKeyChecking=no -i "$PRIVATE_KEY_PATH" "$FILE" "$USERNAME"@"$SERVER_IP":~/
