#!/bin/env bash
# sets up nginx to allow redirections
sudo apt-get update
sudo apt-get install -y nginx
echo "server {
	listen 80;
	location / {
		return 200 '<html>Hello World!</html>\n';
		add_header Content-Type text/html;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > default
sudo cp default /etc/nginx/sites-available/default
sudo service nginx restart
