#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely with sleep 2 in between each iteration and I am invincible!!! when receiving a SIGTERM or SIGINT
trap "echo 'I am invincible!!!'" SIGTERM SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done