#!/usr/bin/env bash
# This script displays 1 to 100 numbers but prints FizzBuzz for multiples of 3 and 5,
# Fizz for multiples of 3 and Buzz for multiples of 5

for i in {1..100}
do
    if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i%3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((i%5)) -eq 0 ]
    then
	echo "Buzz"
    else
	echo "$i"
    fi
done
