#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
#
# Your script should only display:
#
# username
# user id
# Home directory path for the user
# Requirements:
#
# You must use the while loop (for and until are forbidden)

while IFS=: read -r f1 f3 f6
do
    echo "$f1:$f3:$f6"
done < /etc/passwd