#!/usr/bin/env bash
# Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL.
# USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
#
# Requirements:
#
# You must use the while loop (for and until are forbidden)

while IFS=: read -r user password id group info info home command
do
	echo "The user $user is part of the $group gang, lives in $home:$command and rides . $id's place is protected by the passcode $password, more info about the user here: $info."
done < /etc/passwd