#!/usr/bin/env bash

# This script loops from 1 to 10 and:
# displays bad luck for 4th loop iteration
# displays good luck for 8th loop iteration
# displays Best School for all other iterations

for i in {1..10}
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
done
