#!/usr/bin/env bash

# This script that displays numbers from 1 to 20:
# - displays 4 and then Bad luck from China for the 4th loop iteration
# - displays 9 and then good luck from Japan for the 9th loop iteration
# - displays 17 and then good luck from Italy for the 17th loop iteration
# - using only a while loop and using the case statement

i=1
while [ $i -le 20 ]
do
    case $i in
	4)
	    echo "$i Bad luck from China"
	    ;;
	9)
	    echo "$i good luck from Japan"
	    ;;
	17)
	    echo "$i good luck from Italy"
	    ;;
	*)
	    echo "$i"
	    ;;
    esac
    i=$((i+1))
done
