#!/usr/bin/env bash
# This script displays displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 0 to 59
#unsing only a while loop 

i=0
while [ $i -le 12 ]
do
	j=1
	echo "Hour: $i"
	while [ $j -le 59 ]
	do
		echo "$j"
		j=$((j+1))
	done
	i=$((i+1))
done
