#!/usr/bin/env bash

# This script displays displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 0 to 59
#unsing only a while loop 

hour=0
while [ $hour -le 12 ]
do
    minute=0
    while [ $minute -le 59 ]
    do
	if [ $hour -eq 12 ] && [ $minute -eq 59 ]
	then
	    echo "$hour:$minute"
	    break 2
	fi
	echo "$hour:$minute"
	minute=$((minute+1))
    done
    hour=$((hour+1))
done
