#!/usr/bin/env bash
# configures an ubuntu server
CONTAINER_ID=$(docker ps -q)

if [ -z "$CONTAINER_ID" ]; then
    echo "No running Docker container found."
    exit 1
fi

docker cp "$CONTAINER_ID:/etc/hosts" ~/hosts.new

echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

docker cp ~/hosts.new "$CONTAINER_ID:/etc/hosts"

rm ~/hosts.new

docker exec -it "$CONTAINER_ID" cat /etc/hosts

