#!/usr/bin/env bash
# configures an ubuntu server

CONTAINER_ID=$(docker ps -q)

if [ -z "$CONTAINER_ID" ]; then
    echo "No running Docker container found."
    exit 1
fi

TEMP_HOSTS_FILE=$(mktemp):

echo "127.0.0.2 localhost" >> "$TEMP_HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$TEMP_HOSTS_FILE"

docker cp "$TEMP_HOSTS_FILE" "$CONTAINER_ID:/etc/hosts"

rm "$TEMP_HOSTS_FILE"

docker exec -it "$CONTAINER_ID" cat /etc/hosts

